### ISSUE TITLE
The meaning of FSB, TSB, and TSBv

### ISSUE THREAD

**Issue by kongdd** [LiYanStat/dacc#3]
Dear @LiYanStat 

Could you give some explanation about FSB, TSB, and TSBv, which are returned by the function `fingerprint` (<https://rpkgs.github.io/dacc/reference/fingerprint.html>). But I can not figure out their meaning.

**Comment by LiYanStat** [comment]
Those are options for computing the confidence interval for the scaling factors. "FSB" means a bootstrap approach. "TSB" and "TSBv" are two stage bootstrap approach, since we use covariance matrix estimated from an independent set of replicates ahead of the linear regression, there is randomness in the covariance estimate. The two stage bootstrap considers both the randomness in cov estimate and regression model fitting.
